on: [push]
name: Build and Deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Bicep Template
        run: az bicep build --file ./.infrastructure/main.bicep --outfile ./.infrastructure/main.json
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: infrastructure
          path: ./.infrastructure/
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Development
    env:
      environmentName: Deveopment
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: infrastructure
          path: ./.infrastructure/

      - name: Deploy Infrastructure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: ./.infrastructure/main.bicep
          parameters: ${{ format('./.infrastructure/parameters/{0}/parameters.{0}.json', {{ secrets.ENVIRONMENT_NAME }}) }}
          deploymentName: ${{ github.run_id }}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          deploymentScope: ResourceGroup