on:
  push:
  workflow_dispatch:

name: Build and Deploy
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build Bicep Template
  #       run: az bicep build --file ./.infrastructure/main.bicep --outfile ./.infrastructure/main.json
      
  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: infrastructure
  #         path: ./.infrastructure/
  build-infrastructur-and-code:
    name: Build Infrastructure and Code
    uses: ./.github/workflows/build.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}}
    
  deploy-infrastructure-development:
    name: Deploy Infrastructure to Development
    uses: ./.github/workflows/deploy-infrastructure.yml
    needs: build-infrastructur-and-code
    with:
      environment: Development
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}

  deploy-infrastructure-sandbox:
    name: Deploy Infrastructure to Sandbox
    uses: ./.github/workflows/deploy-infrastructure.yml
    needs: build-infrastructur-and-code
    with:
      environment: Sandbox
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  
  deploy-infrastructure-production:
    name: Deploy Infrastructure to Production
    uses: ./.github/workflows/deploy-infrastructure.yml
    needs: [ deploy-infrastructure-development, deploy-infrastructure-sandbox ]
    with:
      environment: Production
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
