on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      RESOURCE_GROUP:
        required: true
      SUBSCRIPTION_ID:
        required: true
      ENVIRONMENT_NAME:
        required: true

jobs:
  deploy-infrastructure-and-functionapp:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      INFRASTRUCTURE_ARTIFACT_PATH: './infrastructure-artifact'
      FUNCTIONAPP_ARTIFACT_PATH: './functionapp-artifact'
      FUNCTIONAPP_NAME: ''
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: infrastructure-artifact
          path: ./infrastructure-artifact/
      
      - name: Download Function App Artifact
        uses: actions/download-artifact@v2
        with:
          name: functionapp-artifact
          path: ./functionapp-artifact/
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: ./${{ env.INFRASTRUCTURE_ARTIFACT_PATH }}/main.bicep
          parameters: ${{ format('{0}/parameters/{1}/parameters.json', env.INFRASTRUCTURE_ARTIFACT_PATH ,secrets.ENVIRONMENT_NAME) }}
          deploymentName: ${{ github.run_id }}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
      
      - name: Deploy Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTIONAPP_NAME }}
          package: ${ env.FUNCTIONAPP_ARTIFACT_PATH }}
